version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/.poetry
    environment:
      MONGODB_HOST: mongodb
      MONGODB_USERNAME: user
      MONGODB_PASSWORD: password123
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password123
